# Generated by Django 4.2.28 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_alert_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_booking_updates_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
