# Generated by Django 4.2.28 on 2026-02-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="ground",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="start_time",
        ),
        migrations.AddField(
            model_name="activitylog",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="slot",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.slot",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.slot",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_source",
            field=models.CharField(
                choices=[("ONLINE", "Online"), ("MANUAL", "Manual")],
                default="ONLINE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="duration_hours",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="BookedSlot",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
