# Generated by Django 4.2.28 on 2026-02-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
