# Generated by Django 4.2.28 on 2026-02-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grounds", "0002_ground_image_ground_latitude_ground_longitude"),
        ("bookings", "0004_booking_reminder_sent"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroundInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("bookings_count", models.PositiveIntegerField()),
                (
                    "charge_per_booking",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ground",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="grounds.ground"
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start", "-ground"],
            },
        ),
    ]
