# Generated by Django 4.2.28 on 2026-02-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_alter_booking_platform_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("BOOKED", "Booked"),
                    ("MANUAL_BOOKING", "Manual Booking"),
                    ("CUSTOMER_CANCELLED", "Customer Cancelled"),
                    ("OWNER_CANCELLED", "Owner Cancelled"),
                    ("CUSTOMER_RESCHEDULED", "Customer Rescheduled"),
                    ("OWNER_RESCHEDULED", "Owner Rescheduled"),
                    ("OWNER_MARKED_PAID", "Owner Marked Paid"),
                    ("ADMIN_ACTION", "Admin Action"),
                ],
                max_length=30,
            ),
        ),
    ]
