# Generated by Codex on 2026-06-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0010_alter_booking_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SHOWED_UP', 'Showed Up'), ('NO_SHOW', 'No Show'), ('UNMARKED', 'Unmarked')], default='UNMARKED', max_length=12)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='bookings.booking')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('MANUAL_BOOKING', 'Manual Booking'), ('CUSTOMER_CANCELLED', 'Customer Cancelled'), ('OWNER_CANCELLED', 'Owner Cancelled'), ('CUSTOMER_RESCHEDULED', 'Customer Rescheduled'), ('OWNER_RESCHEDULED', 'Owner Rescheduled'), ('OWNER_MARKED_PAID', 'Owner Marked Paid'), ('OWNER_MARKED_ATTENDANCE', 'Owner Marked Attendance'), ('ADMIN_ACTION', 'Admin Action')], max_length=30),
        ),
    ]
