# Generated by Django 4.2.28 on 2026-07-10 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0005_groundreview_tournamentregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0011_bookingattendance_activitylog_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='loyalty_reward_redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='reward_discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='reward_points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('BOOKING', 'Booking'), ('FIRST_BOOKING_REFERRAL', 'First Booking Referral'), ('FIRST_TOURNAMENT_REGISTRATION', 'First Tournament Registration'), ('LOYALTY_REDEMPTION', 'Loyalty Redemption')], max_length=40)),
                ('points', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_price_drops', models.BooleanField(default=True)),
                ('notify_last_minute', models.BooleanField(default=True)),
                ('notify_nearby_tournaments', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ground', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to='grounds.ground')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ground')},
            },
        ),
        migrations.CreateModel(
            name='AlertDispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('PRICE_DROP', 'Price Drop'), ('LAST_MINUTE_OPENING', 'Last Minute Opening'), ('TOURNAMENT_PUBLISHED', 'Tournament Published')], max_length=32)),
                ('alert_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ground', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grounds.ground')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grounds.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('ground', 'tournament', 'reason', 'alert_date')},
            },
        ),
    ]
