# Generated by Django 4.2.28 on 2026-07-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_loyalty_reward_redeemed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('FULL', 'Full Payment'), ('PARTIAL_99', 'Advance ₹99'), ('FREE_REWARD', 'Free Booking Credit')], default='FULL', max_length=12),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', 'timestamp'], name='bookings_ac_action_caa4c4_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['booking', 'timestamp'], name='bookings_ac_booking_30758e_idx'),
        ),
        migrations.AddIndex(
            model_name='alertdispatchlog',
            index=models.Index(fields=['ground', 'alert_date'], name='bookings_al_ground__e86509_idx'),
        ),
        migrations.AddIndex(
            model_name='alertdispatchlog',
            index=models.Index(fields=['tournament', 'alert_date'], name='bookings_al_tournam_7cdcf1_idx'),
        ),
        migrations.AddIndex(
            model_name='alertsubscription',
            index=models.Index(fields=['user', 'ground'], name='bookings_al_user_id_84f0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='bookings_bo_status_72dd85_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'slot'], name='bookings_bo_status_98c0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_source', 'created_at'], name='bookings_bo_booking_53cbb7_idx'),
        ),
        migrations.AddIndex(
            model_name='ownerexpense',
            index=models.Index(fields=['owner', 'spent_on'], name='bookings_ow_owner_i_072b91_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['user', 'created_at'], name='bookings_re_user_id_41922b_idx'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['ground', 'date'], name='bookings_sl_ground__7f86e6_idx'),
        ),
    ]
