# Generated by Django 4.2.28 on 2026-07-16 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0015_invoice_and_settlement_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundinvoice',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groundinvoice',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_ground_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='groundinvoice',
            constraint=models.UniqueConstraint(fields=('ground', 'period_start', 'period_end'), name='unique_ground_invoice_period'),
        ),
    ]
