# Generated by Django 4.2.28 on 2026-07-16 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0006_groundreview_grounds_gro_ground__083d7c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0016_groundinvoice_settled_at_groundinvoice_settled_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('booking_count', models.PositiveIntegerField()),
                ('collected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('TRANSFERRED', 'Transferred'), ('ACKNOWLEDGED', 'Acknowledged'), ('DISPUTED', 'Disputed')], default='CREATED', max_length=16)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('admin_note', models.TextField(blank=True)),
                ('owner_note', models.TextField(blank=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('owner_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_online_settlements', to=settings.AUTH_USER_MODEL)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grounds.ground')),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='online_settlements', to=settings.AUTH_USER_MODEL)),
                ('owner_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_online_settlements', to=settings.AUTH_USER_MODEL)),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_online_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineSettlementLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_settlement_line_item', to='bookings.booking')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='bookings.onlinesettlement')),
            ],
            options={
                'ordering': ['booking__slot__date', 'booking__slot__start_time'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='online_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.onlinesettlement'),
        ),
        migrations.AddConstraint(
            model_name='onlinesettlement',
            constraint=models.UniqueConstraint(fields=('ground', 'period_start', 'period_end'), name='unique_online_settlement_period'),
        ),
    ]
