# Generated by Django 4.2.28 on 2026-07-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0003_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='category_fees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/'),
        ),
    ]
