# Generated by Django 4.2.28 on 2026-07-10 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grounds', '0004_tournament_category_fees_tournament_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('headline', models.CharField(blank=True, max_length=120)),
                ('comment', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ground-reviews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='grounds.ground')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120)),
                ('captain_name', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('category_name', models.CharField(max_length=120)),
                ('fee_amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('referral_bonus_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='grounds.tournament')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tournament', 'contact_phone', 'category_name')},
            },
        ),
    ]
