# Generated by Django 4.2.28 on 2026-07-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0005_groundreview_tournamentregistration'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='groundreview',
            index=models.Index(fields=['ground', '-created_at'], name='grounds_gro_ground__083d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['is_published', 'status', 'start_date'], name='grounds_tou_is_publ_114859_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['ground', 'start_date'], name='grounds_tou_ground__fbebf7_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentregistration',
            index=models.Index(fields=['status', 'created_at'], name='grounds_tou_status_46ce86_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentregistration',
            index=models.Index(fields=['tournament', 'created_at'], name='grounds_tou_tournam_b2827a_idx'),
        ),
    ]
