# Generated by Django 4.2.28 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0006_groundreview_grounds_gro_ground__083d7c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='last_minute_price_drop_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
