# Generated by Django 4.2.28 on 2026-08-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0007_ground_last_minute_price_drop_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groundpricing',
            options={'ordering': ['start_time', 'end_time']},
        ),
    ]
